/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mqmessagebrocker;

import com.ibm.mq.MQC;
import com.ibm.mq.MQMessage;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.CustomizedMQMessage;
import utilities.TypesUtilities;
import java.util.List;
import view.MessageDetailFrame;

/**
 *
 * @author jonathan.velez
 */
public class MessageListFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MessageListFrame
     */
    public MessageListFrame()
    {
        initComponents();
    }
    
    public MessageListFrame( ArrayList<MQMessage> messages ) throws IOException
    {
        initComponents();
        loadTable( messages );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMessageList = new JTable() {
            private static final long serialVersionUID = 1L;

            public boolean isCellEditable(int row, int column) {                
                return false;               
            };
        };
        regTotalesLbl = new javax.swing.JLabel();
        regTotCountLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableMessageList.setAutoCreateRowSorter(true);
        tableMessageList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tableMessageList.setAlignmentX(0.0F);
        tableMessageList.setAlignmentY(0.0F);
        tableMessageList.setSurrendersFocusOnKeystroke(true);
        tableMessageList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tableMessagesRowSelected(evt);
            }
        });
        jScrollPane1.setViewportView(tableMessageList);
        tableMessageList.getAccessibleContext().setAccessibleName("");
        tableMessageList.getAccessibleContext().setAccessibleDescription("");

        regTotalesLbl.setText("Registros totales:");

        regTotCountLbl.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(regTotalesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regTotCountLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regTotalesLbl)
                    .addComponent(regTotCountLbl))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMessagesRowSelected(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tableMessagesRowSelected
    {//GEN-HEADEREND:event_tableMessagesRowSelected
        if( evt.getClickCount() == 2 && !evt.isConsumed() )
        {
            if( evt.getButton() == MouseEvent.BUTTON1 )
            {
                evt.consume();
                MessagesListTableModel model = ( MessagesListTableModel ) tableMessageList.getModel();
                
                MessageDetailFrame msd = new MessageDetailFrame( (String) model.getValueAt( tableMessageList.getSelectedRow(),1), (Date) model.getValueAt( tableMessageList.getSelectedRow(),3), (String) model.getValueAt( tableMessageList.getSelectedRow(),2), (String) model.getValueAt( tableMessageList.getSelectedRow(),4) );
                msd.setLocationRelativeTo( this );
                msd.setVisible( true );                
            }
            else if( evt.getButton() == MouseEvent.BUTTON3 )
            {
                evt.consume();
                JOptionPane.showMessageDialog(this, "Esta funcionalidad está en construcción.", "Información", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tableMessagesRowSelected

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( MessageListFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( MessageListFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( MessageListFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        catch( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( MessageListFrame.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new MessageListFrame().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel regTotCountLbl;
    private javax.swing.JLabel regTotalesLbl;
    private javax.swing.JTable tableMessageList;
    // End of variables declaration//GEN-END:variables

    private void loadTable( ArrayList<MQMessage> messages ) throws IOException
    {
        int i = 0;
        MessagesListTableModel model;
        List rowlist = new ArrayList();
        ArrayList<String> row = new ArrayList<String>();
        
        for( MQMessage msj : messages )
        {
            CustomizedMQMessage customMessage = new CustomizedMQMessage( msj );
            customMessage.setNumber( ++i );
            rowlist.add( customMessage );
        }
        model = new MessagesListTableModel( rowlist );
        regTotCountLbl.setText( Integer.toString( messages.size() ) );
        tableMessageList.setModel( model );        
//        tableMessageList.setVisible( true );
    }
}
